# Generated by Django 6.0.6 on 2026-06-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Select title for blog')),
                ('subject', models.CharField(choices=[('Number theory', 'Number theory'), ('Algebra', 'Algebra'), ('Combinatorics', 'Combinatorics'), ('Geometry', 'Geometry')], default='Algebra', max_length=100, verbose_name='Chose subject')),
                ('description', models.TextField(verbose_name='Give blog description')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Select news title')),
                ('photo', models.ImageField(upload_to='news_mk/', verbose_name='Upload photo')),
                ('source', models.URLField(verbose_name='Upload source link')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
